/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Config */
        get: operations["config_api_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Uploads */
        get: operations["list_uploads_api_uploads_get"];
        put?: never;
        /** Create Upload */
        post: operations["create_upload_api_uploads_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/uploads/{upload_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Upload */
        get: operations["get_upload_api_uploads__upload_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Upload
         * @description Delete an upload and the shipments that came only from it. Shipments also present in another
         *     upload are kept.
         */
        delete: operations["delete_upload_api_uploads__upload_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/uploads/{upload_id}/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Preview Upload */
        get: operations["preview_upload_api_uploads__upload_id__preview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/uploads/{upload_id}/commit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Commit Upload */
        post: operations["commit_upload_api_uploads__upload_id__commit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/presets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Presets */
        get: operations["list_presets_api_presets_get"];
        put?: never;
        /** Create Preset */
        post: operations["create_preset_api_presets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/presets/{preset_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Preset */
        put: operations["update_preset_api_presets__preset_id__put"];
        post?: never;
        /** Delete Preset */
        delete: operations["delete_preset_api_presets__preset_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shipments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Shipments */
        get: operations["list_shipments_api_shipments_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shipments/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stats */
        get: operations["stats_api_shipments_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shipments/facets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Facets */
        get: operations["facets_api_shipments_facets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shipments/{shipment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Shipment */
        get: operations["get_shipment_api_shipments__shipment_id__get"];
        put?: never;
        post?: never;
        /** Delete Shipment */
        delete: operations["delete_shipment_api_shipments__shipment_id__delete"];
        options?: never;
        head?: never;
        /** Patch Shipment */
        patch: operations["patch_shipment_api_shipments__shipment_id__patch"];
        trace?: never;
    };
    "/api/shipments/{shipment_id}/path.geojson": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Shipment Path
         * @description Origin -> scan locations (chronological, deduped by place) -> destination, as a FeatureCollection.
         */
        get: operations["shipment_path_api_shipments__shipment_id__path_geojson_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shipments/{shipment_id}/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh Shipment */
        post: operations["refresh_shipment_api_shipments__shipment_id__refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shipments/{shipment_id}/notes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Note */
        post: operations["add_note_api_shipments__shipment_id__notes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notes/{note_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Edit Note */
        put: operations["edit_note_api_notes__note_id__put"];
        post?: never;
        /** Delete Note */
        delete: operations["delete_note_api_notes__note_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tags */
        get: operations["list_tags_api_tags_get"];
        put?: never;
        /** Create Tag */
        post: operations["create_tag_api_tags_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tags/{tag_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Tag */
        put: operations["update_tag_api_tags__tag_id__put"];
        post?: never;
        /** Delete Tag */
        delete: operations["delete_tag_api_tags__tag_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shipments/{shipment_id}/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set Tags */
        put: operations["set_tags_api_shipments__shipment_id__tags_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/map/points.geojson": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Points */
        get: operations["points_api_map_points_geojson_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/map/states": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** States */
        get: operations["states_api_map_states_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Refresh */
        post: operations["start_refresh_api_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Jobs */
        get: operations["list_jobs_api_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current Job */
        get: operations["current_job_api_jobs_current_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Job */
        post: operations["cancel_job_api_jobs__job_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/attention": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Attention */
        get: operations["attention_api_attention_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export */
        get: operations["export_api_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get General */
        get: operations["get_general_api_settings_get"];
        /** Put General */
        put: operations["put_general_api_settings_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/carriers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Carriers */
        get: operations["get_carriers_api_settings_carriers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/carriers/{carrier}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Put Carrier */
        put: operations["put_carrier_api_settings_carriers__carrier__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/carriers/{carrier}/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Test Carrier */
        post: operations["test_carrier_api_settings_carriers__carrier__test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/geocoder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Geocoder */
        get: operations["get_geocoder_api_settings_geocoder_get"];
        /** Put Geocoder */
        put: operations["put_geocoder_api_settings_geocoder_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/geocoder/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Test Geocoder */
        post: operations["test_geocoder_api_settings_geocoder_test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/privacy/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Summary */
        get: operations["summary_api_privacy_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/privacy/egress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Egress */
        get: operations["egress_api_privacy_egress_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/privacy/wipe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Wipe
         * @description Delete every shipment, upload, event, note, tag, job and cached geocode. Optionally keep settings.
         */
        post: operations["wipe_api_privacy_wipe_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AttentionRow */
        AttentionRow: {
            /** Id */
            id: number;
            /** Tracking Number */
            tracking_number: string;
            /** Carrier */
            carrier: string;
            /** Carrier Confidence */
            carrier_confidence: number;
            /** Recipient Name */
            recipient_name: string | null;
            /** Company */
            company: string | null;
            /** Address1 */
            address1: string | null;
            /** Address2 */
            address2: string | null;
            /** City */
            city: string | null;
            /** State */
            state: string | null;
            /** Postal Code */
            postal_code: string | null;
            /** Country */
            country: string;
            /** Order Ref */
            order_ref: string | null;
            /** Ship Date */
            ship_date: string | null;
            /** Status */
            status: string;
            /** Status Raw */
            status_raw: string | null;
            /** Attention Flag */
            attention_flag: string | null;
            /** Expected Delivery */
            expected_delivery: string | null;
            /** Delivered At */
            delivered_at: string | null;
            /** Last Event At */
            last_event_at: string | null;
            /** Last Event Desc */
            last_event_desc: string | null;
            /** Last Event Place */
            last_event_place: string | null;
            /** Dest Lat */
            dest_lat: number | null;
            /** Dest Lng */
            dest_lng: number | null;
            /** Geocode Precision */
            geocode_precision: string;
            /** Last Polled At */
            last_polled_at: string | null;
            /** Poll Error Count */
            poll_error_count: number;
            /** Poll Last Error */
            poll_last_error: string | null;
            /** Days In Transit */
            days_in_transit?: number | null;
            /**
             * Tags
             * @default []
             */
            tags: components["schemas"]["TagOut"][];
            /**
             * Upload Ids
             * @default []
             */
            upload_ids: number[];
            /** Carrier Url */
            carrier_url?: string | null;
            /**
             * Reasons
             * @default []
             */
            reasons: string[];
        };
        /** Body_create_upload_api_uploads_post */
        Body_create_upload_api_uploads_post: {
            /**
             * File
             * Format: binary
             */
            file: string;
        };
        /**
         * Carrier
         * @enum {string}
         */
        Carrier: "usps" | "fedex" | "unknown";
        /** CarrierSettingsIn */
        CarrierSettingsIn: {
            /** Enabled */
            enabled?: boolean | null;
            /** Mode */
            mode?: string | null;
            /** Sandbox */
            sandbox?: boolean | null;
            /** Client Id */
            client_id?: string | null;
            /** Client Secret */
            client_secret?: string | null;
        };
        /** CarrierSettingsOut */
        CarrierSettingsOut: {
            /** Carrier */
            carrier: string;
            /** Enabled */
            enabled: boolean;
            /** Mode */
            mode: string;
            /** Sandbox */
            sandbox: boolean;
            /** Client Id */
            client_id: string | null;
            /** Client Secret Masked */
            client_secret_masked: string | null;
            /** Has Secret */
            has_secret: boolean;
            /** From Env */
            from_env: boolean;
            /** Status */
            status: string;
            /** Last Check At */
            last_check_at: string | null;
            /** Last Check Ok */
            last_check_ok: boolean | null;
            /** Last Check Message */
            last_check_message: string | null;
        };
        /** CommitRequest */
        CommitRequest: {
            /** Sheet */
            sheet?: string | null;
            /**
             * Header Row
             * @default 0
             */
            header_row: number;
            /** Mapping */
            mapping?: {
                [key: string]: string;
            };
            /**
             * Geocode Mode
             * @default offline
             */
            geocode_mode: string;
            /** Default Carrier */
            default_carrier?: string | null;
            /** Save Preset As */
            save_preset_as?: string | null;
            /** Preset Id */
            preset_id?: number | null;
        };
        /** CommitResult */
        CommitResult: {
            upload: components["schemas"]["UploadOut"];
            /** Imported */
            imported: number;
            /** Duplicates */
            duplicates: number;
            /** Skipped */
            skipped: number;
            /** Errors */
            errors: {
                [key: string]: unknown;
            }[];
            /** Geocode Job Id */
            geocode_job_id?: number | null;
        };
        /** CredentialCheck */
        CredentialCheck: {
            /** Ok */
            ok: boolean;
            /** Message */
            message: string;
        };
        /** EgressOut */
        EgressOut: {
            /** Host */
            host: string;
            /** Purpose */
            purpose: string;
            /** Data Classes */
            data_classes: string;
            /** Count */
            count: number;
            /**
             * First At
             * Format: date-time
             */
            first_at: string;
            /**
             * Last At
             * Format: date-time
             */
            last_at: string;
            /** Last Status */
            last_status: string | null;
        };
        /** EventOut */
        EventOut: {
            /** Id */
            id: number;
            /** Event At */
            event_at: string | null;
            /** Event At Raw */
            event_at_raw: string | null;
            /** Code */
            code: string | null;
            /** Description */
            description: string;
            /** Normalized Status */
            normalized_status: string;
            /** City */
            city: string | null;
            /** State */
            state: string | null;
            /** Postal Code */
            postal_code: string | null;
            /** Country */
            country: string | null;
            /** Lat */
            lat: number | null;
            /** Lng */
            lng: number | null;
        };
        /** Facets */
        Facets: {
            /** States */
            states: string[];
            /** Cities */
            cities: string[];
            /** Carriers */
            carriers: string[];
            /** Uploads */
            uploads: {
                [key: string]: unknown;
            }[];
            /** Tags */
            tags: components["schemas"]["TagOut"][];
            /** Statuses */
            statuses: string[];
        };
        /** GeneralSettings */
        GeneralSettings: {
            /** Stuck Days */
            stuck_days?: number | null;
            /** Origin Postal Code */
            origin_postal_code?: string | null;
            /** Map Style Url */
            map_style_url?: string | null;
            /** Map Style Url Dark */
            map_style_url_dark?: string | null;
        };
        /** GeocoderSettingsIn */
        GeocoderSettingsIn: {
            /** Provider */
            provider?: string | null;
            /** Api Key */
            api_key?: string | null;
            /** Nominatim Email */
            nominatim_email?: string | null;
        };
        /** GeocoderSettingsOut */
        GeocoderSettingsOut: {
            /** Provider */
            provider: string;
            /** Api Key Masked */
            api_key_masked: string | null;
            /** Has Key */
            has_key: boolean;
            /** Nominatim Email */
            nominatim_email: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** JobOut */
        JobOut: {
            /** Id */
            id: number;
            /** Kind */
            kind: string;
            /** Status */
            status: string;
            /** Total */
            total: number;
            /** Done */
            done: number;
            /** Updated */
            updated: number;
            /** Errors */
            errors: number;
            /** Message */
            message: string | null;
            /** Error Samples */
            error_samples?: string[];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
        };
        /** NoteIn */
        NoteIn: {
            /** Body */
            body: string;
        };
        /** NoteOut */
        NoteOut: {
            /** Id */
            id: number;
            /** Body */
            body: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** Page[ShipmentRow] */
        Page_ShipmentRow_: {
            /** Items */
            items: components["schemas"]["ShipmentRow"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /** PresetIn */
        PresetIn: {
            /** Name */
            name: string;
            /** Mapping */
            mapping: {
                [key: string]: string;
            };
            /** Headers */
            headers?: string[] | null;
        };
        /** PresetOut */
        PresetOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Mapping */
            mapping: {
                [key: string]: unknown;
            };
            /** Header Signature */
            header_signature: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Last Used At */
            last_used_at: string | null;
        };
        /** PrivacySummary */
        PrivacySummary: {
            /** Data Dir */
            data_dir: string;
            /** Db Size Bytes */
            db_size_bytes: number;
            /** Uploads Size Bytes */
            uploads_size_bytes: number;
            /** Shipments */
            shipments: number;
            /** Uploads */
            uploads: number;
            /** Events */
            events: number;
            /** Secrets */
            secrets: {
                [key: string]: unknown;
            }[];
            /** Tile Host */
            tile_host: string;
            /** Geocoder */
            geocoder: string;
            /** Auth Enabled */
            auth_enabled: boolean;
            /** Egress */
            egress: {
                [key: string]: unknown;
            }[];
            /** Wipe Token */
            wipe_token: string;
        };
        /** RefreshRequest */
        RefreshRequest: {
            /**
             * All
             * @default false
             */
            all: boolean;
            /** Shipment Ids */
            shipment_ids?: number[] | null;
            /** Filters */
            filters?: {
                [key: string]: unknown;
            } | null;
            /**
             * Include Terminal
             * @default false
             */
            include_terminal: boolean;
        };
        /** RefreshStarted */
        RefreshStarted: {
            /** Job Id */
            job_id: number | null;
            /** Queued */
            queued: number;
        };
        /** ShipmentDetail */
        ShipmentDetail: {
            /** Id */
            id: number;
            /** Tracking Number */
            tracking_number: string;
            /** Carrier */
            carrier: string;
            /** Carrier Confidence */
            carrier_confidence: number;
            /** Recipient Name */
            recipient_name: string | null;
            /** Company */
            company: string | null;
            /** Address1 */
            address1: string | null;
            /** Address2 */
            address2: string | null;
            /** City */
            city: string | null;
            /** State */
            state: string | null;
            /** Postal Code */
            postal_code: string | null;
            /** Country */
            country: string;
            /** Order Ref */
            order_ref: string | null;
            /** Ship Date */
            ship_date: string | null;
            /** Status */
            status: string;
            /** Status Raw */
            status_raw: string | null;
            /** Attention Flag */
            attention_flag: string | null;
            /** Expected Delivery */
            expected_delivery: string | null;
            /** Delivered At */
            delivered_at: string | null;
            /** Last Event At */
            last_event_at: string | null;
            /** Last Event Desc */
            last_event_desc: string | null;
            /** Last Event Place */
            last_event_place: string | null;
            /** Dest Lat */
            dest_lat: number | null;
            /** Dest Lng */
            dest_lng: number | null;
            /** Geocode Precision */
            geocode_precision: string;
            /** Last Polled At */
            last_polled_at: string | null;
            /** Poll Error Count */
            poll_error_count: number;
            /** Poll Last Error */
            poll_last_error: string | null;
            /** Days In Transit */
            days_in_transit?: number | null;
            /**
             * Tags
             * @default []
             */
            tags: components["schemas"]["TagOut"][];
            /**
             * Upload Ids
             * @default []
             */
            upload_ids: number[];
            /** Carrier Url */
            carrier_url?: string | null;
            /** Email */
            email: string | null;
            /** Phone */
            phone: string | null;
            /** Origin Postal Code */
            origin_postal_code: string | null;
            /** Status Code */
            status_code: string | null;
            /** First Event At */
            first_event_at: string | null;
            /** Carrier Locked */
            carrier_locked: boolean;
            /** Geocode Source */
            geocode_source: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Events
             * @default []
             */
            events: components["schemas"]["EventOut"][];
            /**
             * Notes
             * @default []
             */
            notes: components["schemas"]["NoteOut"][];
            /**
             * Uploads
             * @default []
             */
            uploads: components["schemas"]["UploadRef"][];
        };
        /** ShipmentPatch */
        ShipmentPatch: {
            /** Carrier */
            carrier?: string | null;
            /** Recipient Name */
            recipient_name?: string | null;
            /** Company */
            company?: string | null;
            /** Address1 */
            address1?: string | null;
            /** Address2 */
            address2?: string | null;
            /** City */
            city?: string | null;
            /** State */
            state?: string | null;
            /** Postal Code */
            postal_code?: string | null;
            /** Order Ref */
            order_ref?: string | null;
            /** Ship Date */
            ship_date?: string | null;
            /** Email */
            email?: string | null;
            /** Phone */
            phone?: string | null;
        };
        /** ShipmentRow */
        ShipmentRow: {
            /** Id */
            id: number;
            /** Tracking Number */
            tracking_number: string;
            /** Carrier */
            carrier: string;
            /** Carrier Confidence */
            carrier_confidence: number;
            /** Recipient Name */
            recipient_name: string | null;
            /** Company */
            company: string | null;
            /** Address1 */
            address1: string | null;
            /** Address2 */
            address2: string | null;
            /** City */
            city: string | null;
            /** State */
            state: string | null;
            /** Postal Code */
            postal_code: string | null;
            /** Country */
            country: string;
            /** Order Ref */
            order_ref: string | null;
            /** Ship Date */
            ship_date: string | null;
            /** Status */
            status: string;
            /** Status Raw */
            status_raw: string | null;
            /** Attention Flag */
            attention_flag: string | null;
            /** Expected Delivery */
            expected_delivery: string | null;
            /** Delivered At */
            delivered_at: string | null;
            /** Last Event At */
            last_event_at: string | null;
            /** Last Event Desc */
            last_event_desc: string | null;
            /** Last Event Place */
            last_event_place: string | null;
            /** Dest Lat */
            dest_lat: number | null;
            /** Dest Lng */
            dest_lng: number | null;
            /** Geocode Precision */
            geocode_precision: string;
            /** Last Polled At */
            last_polled_at: string | null;
            /** Poll Error Count */
            poll_error_count: number;
            /** Poll Last Error */
            poll_last_error: string | null;
            /** Days In Transit */
            days_in_transit?: number | null;
            /**
             * Tags
             * @default []
             */
            tags: components["schemas"]["TagOut"][];
            /**
             * Upload Ids
             * @default []
             */
            upload_ids: number[];
            /** Carrier Url */
            carrier_url?: string | null;
        };
        /** Stats */
        Stats: {
            /** Total */
            total: number;
            /** By Status */
            by_status: {
                [key: string]: number;
            };
            /** By Carrier */
            by_carrier: {
                [key: string]: number;
            };
            /** Delivered Last 7D */
            delivered_last_7d: number;
            /** Attention */
            attention: number;
            /** Avg Days In Transit */
            avg_days_in_transit: number | null;
            /** Median Days In Transit */
            median_days_in_transit: number | null;
            /** Not Geocoded */
            not_geocoded: number;
            /** Last Polled At */
            last_polled_at: string | null;
        };
        /** TagIn */
        TagIn: {
            /** Name */
            name: string;
            /** Color */
            color?: string | null;
        };
        /** TagOut */
        TagOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Color */
            color: string;
        };
        /** TagsSet */
        TagsSet: {
            /** Tags */
            tags: string[];
        };
        /** UploadOut */
        UploadOut: {
            /** Id */
            id: number;
            /** Filename */
            filename: string;
            /** Size Bytes */
            size_bytes: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Committed At */
            committed_at: string | null;
            /** Status */
            status: string;
            /** Sheet Name */
            sheet_name: string | null;
            /** Header Row */
            header_row: number;
            /** Column Mapping */
            column_mapping: {
                [key: string]: unknown;
            } | null;
            /** Preset Id */
            preset_id: number | null;
            /** Geocode Mode */
            geocode_mode: string;
            /** Default Carrier */
            default_carrier: string | null;
            /** Row Count */
            row_count: number;
            /** Imported Count */
            imported_count: number;
            /** Duplicate Count */
            duplicate_count: number;
            /** Skipped Count */
            skipped_count: number;
            /** Errors */
            errors: unknown[] | null;
            /**
             * Shipment Count
             * @default 0
             */
            shipment_count: number;
        };
        /** UploadPreview */
        UploadPreview: {
            /** Upload Id */
            upload_id: number;
            /** Filename */
            filename: string;
            /** Sheets */
            sheets: string[];
            /** Sheet */
            sheet: string;
            /** Header Row */
            header_row: number;
            /** Headers */
            headers: string[];
            /** Sample Rows */
            sample_rows: string[][];
            /** Row Count */
            row_count: number;
            /** Suggested Mapping */
            suggested_mapping: {
                [key: string]: string;
            };
            /** Matched Preset Id */
            matched_preset_id: number | null;
            /** Fields */
            fields: {
                [key: string]: unknown;
            }[];
            /** Carrier Detection */
            carrier_detection: {
                [key: string]: unknown;
            };
        };
        /** UploadRef */
        UploadRef: {
            /** Id */
            id: number;
            /** Filename */
            filename: string;
            /** Row Number */
            row_number: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WipeRequest */
        WipeRequest: {
            /** Token */
            token: string;
            /**
             * Keep Settings
             * @default true
             */
            keep_settings: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    config_api_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    list_uploads_api_uploads_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadOut"][];
                };
            };
        };
    };
    create_upload_api_uploads_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_upload_api_uploads_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadPreview"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_upload_api_uploads__upload_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                upload_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_upload_api_uploads__upload_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                upload_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_upload_api_uploads__upload_id__preview_get: {
        parameters: {
            query?: {
                sheet?: string | null;
                header_row?: number | null;
            };
            header?: never;
            path: {
                upload_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadPreview"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    commit_upload_api_uploads__upload_id__commit_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                upload_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommitRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommitResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_presets_api_presets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PresetOut"][];
                };
            };
        };
    };
    create_preset_api_presets_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PresetIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PresetOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_preset_api_presets__preset_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                preset_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PresetIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PresetOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_preset_api_presets__preset_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                preset_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_shipments_api_shipments_get: {
        parameters: {
            query?: {
                sort?: string | null;
                page?: number;
                page_size?: number;
                status?: string[] | null;
                carrier?: string[] | null;
                upload_id?: string[] | null;
                state?: string[] | null;
                tag?: string[] | null;
                city?: string | null;
                q?: string | null;
                ship_date_from?: string | null;
                ship_date_to?: string | null;
                last_event_from?: string | null;
                last_event_to?: string | null;
                days_min?: number | null;
                days_max?: number | null;
                attention?: boolean | null;
                geocoded?: boolean | null;
                ids?: string[] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_ShipmentRow_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stats_api_shipments_stats_get: {
        parameters: {
            query?: {
                status?: string[] | null;
                carrier?: string[] | null;
                upload_id?: string[] | null;
                state?: string[] | null;
                tag?: string[] | null;
                city?: string | null;
                q?: string | null;
                ship_date_from?: string | null;
                ship_date_to?: string | null;
                last_event_from?: string | null;
                last_event_to?: string | null;
                days_min?: number | null;
                days_max?: number | null;
                attention?: boolean | null;
                geocoded?: boolean | null;
                ids?: string[] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Stats"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    facets_api_shipments_facets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Facets"];
                };
            };
        };
    };
    get_shipment_api_shipments__shipment_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                shipment_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShipmentDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_shipment_api_shipments__shipment_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                shipment_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_shipment_api_shipments__shipment_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                shipment_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ShipmentPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShipmentDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    shipment_path_api_shipments__shipment_id__path_geojson_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                shipment_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_shipment_api_shipments__shipment_id__refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                shipment_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShipmentDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_note_api_shipments__shipment_id__notes_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                shipment_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NoteIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShipmentDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edit_note_api_notes__note_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                note_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NoteIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoteOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_note_api_notes__note_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                note_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tags_api_tags_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagOut"][];
                };
            };
        };
    };
    create_tag_api_tags_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TagIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_tag_api_tags__tag_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tag_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TagIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_tag_api_tags__tag_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tag_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_tags_api_shipments__shipment_id__tags_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                shipment_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TagsSet"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShipmentDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    points_api_map_points_geojson_get: {
        parameters: {
            query?: {
                status?: string[] | null;
                carrier?: string[] | null;
                upload_id?: string[] | null;
                state?: string[] | null;
                tag?: string[] | null;
                city?: string | null;
                q?: string | null;
                ship_date_from?: string | null;
                ship_date_to?: string | null;
                last_event_from?: string | null;
                last_event_to?: string | null;
                days_min?: number | null;
                days_max?: number | null;
                attention?: boolean | null;
                geocoded?: boolean | null;
                ids?: string[] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    states_api_map_states_get: {
        parameters: {
            query?: {
                status?: string[] | null;
                carrier?: string[] | null;
                upload_id?: string[] | null;
                state?: string[] | null;
                tag?: string[] | null;
                city?: string | null;
                q?: string | null;
                ship_date_from?: string | null;
                ship_date_to?: string | null;
                last_event_from?: string | null;
                last_event_to?: string | null;
                days_min?: number | null;
                days_max?: number | null;
                attention?: boolean | null;
                geocoded?: boolean | null;
                ids?: string[] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_refresh_api_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefreshStarted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_jobs_api_jobs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"][];
                };
            };
        };
    };
    current_job_api_jobs_current_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"] | null;
                };
            };
        };
    };
    get_job_api_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_job_api_jobs__job_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    attention_api_attention_get: {
        parameters: {
            query?: {
                sort?: string | null;
                limit?: number;
                status?: string[] | null;
                carrier?: string[] | null;
                upload_id?: string[] | null;
                state?: string[] | null;
                tag?: string[] | null;
                city?: string | null;
                q?: string | null;
                ship_date_from?: string | null;
                ship_date_to?: string | null;
                last_event_from?: string | null;
                last_event_to?: string | null;
                days_min?: number | null;
                days_max?: number | null;
                attention?: boolean | null;
                geocoded?: boolean | null;
                ids?: string[] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttentionRow"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_api_export_get: {
        parameters: {
            query?: {
                format?: string;
                columns?: string | null;
                sort?: string | null;
                status?: string[] | null;
                carrier?: string[] | null;
                upload_id?: string[] | null;
                state?: string[] | null;
                tag?: string[] | null;
                city?: string | null;
                q?: string | null;
                ship_date_from?: string | null;
                ship_date_to?: string | null;
                last_event_from?: string | null;
                last_event_to?: string | null;
                days_min?: number | null;
                days_max?: number | null;
                attention?: boolean | null;
                geocoded?: boolean | null;
                ids?: string[] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_general_api_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeneralSettings"];
                };
            };
        };
    };
    put_general_api_settings_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GeneralSettings"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeneralSettings"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_carriers_api_settings_carriers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CarrierSettingsOut"][];
                };
            };
        };
    };
    put_carrier_api_settings_carriers__carrier__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                carrier: components["schemas"]["Carrier"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CarrierSettingsIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CarrierSettingsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    test_carrier_api_settings_carriers__carrier__test_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                carrier: components["schemas"]["Carrier"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CredentialCheck"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_geocoder_api_settings_geocoder_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeocoderSettingsOut"];
                };
            };
        };
    };
    put_geocoder_api_settings_geocoder_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GeocoderSettingsIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeocoderSettingsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    test_geocoder_api_settings_geocoder_test_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CredentialCheck"];
                };
            };
        };
    };
    summary_api_privacy_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PrivacySummary"];
                };
            };
        };
    };
    egress_api_privacy_egress_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EgressOut"][];
                };
            };
        };
    };
    wipe_api_privacy_wipe_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WipeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
