"""initial schema

Revision ID: 794d3b8d94c3
Revises:
Create Date: 2026-09-03 02:21:04.329793
"""

from __future__ import annotations

import sqlalchemy as sa

from alembic import op

revision = "794d3b8d94c3"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "carrier_credentials",
        sa.Column("carrier", sa.String(length=20), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("mode", sa.String(length=10), nullable=False),
        sa.Column("sandbox", sa.Boolean(), nullable=False),
        sa.Column("client_id", sa.String(length=255), nullable=True),
        sa.Column("client_secret_enc", sa.Text(), nullable=True),
        sa.Column("access_token_enc", sa.Text(), nullable=True),
        sa.Column("token_expires_at", sa.DateTime(), nullable=True),
        sa.Column("last_check_at", sa.DateTime(), nullable=True),
        sa.Column("last_check_ok", sa.Boolean(), nullable=True),
        sa.Column("last_check_message", sa.String(length=500), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("carrier"),
    )
    op.create_table(
        "column_presets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("mapping", sa.JSON(), nullable=False),
        sa.Column("header_signature", sa.String(length=40), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("last_used_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    with op.batch_alter_table("column_presets", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_column_presets_header_signature"), ["header_signature"], unique=False
        )

    op.create_table(
        "egress_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("host", sa.String(length=255), nullable=False),
        sa.Column("purpose", sa.String(length=60), nullable=False),
        sa.Column("data_classes", sa.String(length=120), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.Column("first_at", sa.DateTime(), nullable=False),
        sa.Column("last_at", sa.DateTime(), nullable=False),
        sa.Column("last_status", sa.String(length=20), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("host", "purpose", name="uq_egress_host_purpose"),
    )
    op.create_table(
        "geocode_cache",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("query_key", sa.String(length=500), nullable=False),
        sa.Column("source", sa.String(length=30), nullable=False),
        sa.Column("lat", sa.Float(), nullable=True),
        sa.Column("lng", sa.Float(), nullable=True),
        sa.Column("precision", sa.String(length=10), nullable=False),
        sa.Column("raw", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("query_key", "source", name="uq_geocode_query"),
    )
    op.create_table(
        "jobs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("total", sa.Integer(), nullable=False),
        sa.Column("done", sa.Integer(), nullable=False),
        sa.Column("updated", sa.Integer(), nullable=False),
        sa.Column("errors", sa.Integer(), nullable=False),
        sa.Column("error_sample", sa.JSON(), nullable=True),
        sa.Column("message", sa.String(length=500), nullable=True),
        sa.Column("cancel_requested", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "settings",
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("value", sa.JSON(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "shipments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tracking_number", sa.String(length=64), nullable=False),
        sa.Column("carrier", sa.String(length=20), nullable=False),
        sa.Column("carrier_confidence", sa.Float(), nullable=False),
        sa.Column("carrier_locked", sa.Boolean(), nullable=False),
        sa.Column("recipient_name", sa.String(length=255), nullable=True),
        sa.Column("company", sa.String(length=255), nullable=True),
        sa.Column("address1", sa.String(length=255), nullable=True),
        sa.Column("address2", sa.String(length=255), nullable=True),
        sa.Column("city", sa.String(length=120), nullable=True),
        sa.Column("state", sa.String(length=2), nullable=True),
        sa.Column("postal_code", sa.String(length=10), nullable=True),
        sa.Column("country", sa.String(length=2), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("phone", sa.String(length=50), nullable=True),
        sa.Column("order_ref", sa.String(length=120), nullable=True),
        sa.Column("ship_date", sa.Date(), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("status_raw", sa.String(length=255), nullable=True),
        sa.Column("status_code", sa.String(length=30), nullable=True),
        sa.Column("attention_flag", sa.String(length=30), nullable=True),
        sa.Column("expected_delivery", sa.Date(), nullable=True),
        sa.Column("delivered_at", sa.DateTime(), nullable=True),
        sa.Column("first_event_at", sa.DateTime(), nullable=True),
        sa.Column("last_event_at", sa.DateTime(), nullable=True),
        sa.Column("last_event_desc", sa.String(length=500), nullable=True),
        sa.Column("last_event_place", sa.String(length=255), nullable=True),
        sa.Column("origin_postal_code", sa.String(length=10), nullable=True),
        sa.Column("dest_lat", sa.Float(), nullable=True),
        sa.Column("dest_lng", sa.Float(), nullable=True),
        sa.Column("geocode_precision", sa.String(length=10), nullable=False),
        sa.Column("geocode_source", sa.String(length=30), nullable=True),
        sa.Column("last_polled_at", sa.DateTime(), nullable=True),
        sa.Column("poll_error_count", sa.Integer(), nullable=False),
        sa.Column("poll_last_error", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tracking_number"),
    )
    with op.batch_alter_table("shipments", schema=None) as batch_op:
        batch_op.create_index("ix_shipments_carrier", ["carrier"], unique=False)
        batch_op.create_index("ix_shipments_last_event_at", ["last_event_at"], unique=False)
        batch_op.create_index("ix_shipments_recipient_name", ["recipient_name"], unique=False)
        batch_op.create_index("ix_shipments_ship_date", ["ship_date"], unique=False)
        batch_op.create_index("ix_shipments_state", ["state"], unique=False)
        batch_op.create_index("ix_shipments_status", ["status"], unique=False)

    op.create_table(
        "tags",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=60), nullable=False),
        sa.Column("color", sa.String(length=20), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "notes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("shipment_id", sa.Integer(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["shipment_id"], ["shipments.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("notes", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_notes_shipment_id"), ["shipment_id"], unique=False)

    op.create_table(
        "shipment_tags",
        sa.Column("shipment_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["shipment_id"], ["shipments.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tag_id"], ["tags.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("shipment_id", "tag_id"),
    )
    op.create_table(
        "tracking_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("shipment_id", sa.Integer(), nullable=False),
        sa.Column("event_at", sa.DateTime(), nullable=True),
        sa.Column("event_at_raw", sa.String(length=64), nullable=True),
        sa.Column("code", sa.String(length=30), nullable=True),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("normalized_status", sa.String(length=30), nullable=False),
        sa.Column("city", sa.String(length=120), nullable=True),
        sa.Column("state", sa.String(length=2), nullable=True),
        sa.Column("postal_code", sa.String(length=10), nullable=True),
        sa.Column("country", sa.String(length=2), nullable=True),
        sa.Column("lat", sa.Float(), nullable=True),
        sa.Column("lng", sa.Float(), nullable=True),
        sa.Column("raw", sa.JSON(), nullable=True),
        sa.Column("dedupe_key", sa.String(length=40), nullable=False),
        sa.ForeignKeyConstraint(["shipment_id"], ["shipments.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("shipment_id", "dedupe_key", name="uq_event_dedupe"),
    )
    with op.batch_alter_table("tracking_events", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_tracking_events_shipment_id"), ["shipment_id"], unique=False)

    op.create_table(
        "uploads",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("committed_at", sa.DateTime(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("sheet_name", sa.String(length=255), nullable=True),
        sa.Column("header_row", sa.Integer(), nullable=False),
        sa.Column("column_mapping", sa.JSON(), nullable=True),
        sa.Column("preset_id", sa.Integer(), nullable=True),
        sa.Column("geocode_mode", sa.String(length=20), nullable=False),
        sa.Column("default_carrier", sa.String(length=20), nullable=True),
        sa.Column("row_count", sa.Integer(), nullable=False),
        sa.Column("imported_count", sa.Integer(), nullable=False),
        sa.Column("duplicate_count", sa.Integer(), nullable=False),
        sa.Column("skipped_count", sa.Integer(), nullable=False),
        sa.Column("errors", sa.JSON(), nullable=True),
        sa.Column("raw_path", sa.String(length=500), nullable=True),
        sa.ForeignKeyConstraint(["preset_id"], ["column_presets.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "shipment_uploads",
        sa.Column("shipment_id", sa.Integer(), nullable=False),
        sa.Column("upload_id", sa.Integer(), nullable=False),
        sa.Column("row_number", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["shipment_id"], ["shipments.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["upload_id"], ["uploads.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("shipment_id", "upload_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("shipment_uploads")
    op.drop_table("uploads")
    with op.batch_alter_table("tracking_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tracking_events_shipment_id"))

    op.drop_table("tracking_events")
    op.drop_table("shipment_tags")
    with op.batch_alter_table("notes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_notes_shipment_id"))

    op.drop_table("notes")
    op.drop_table("tags")
    with op.batch_alter_table("shipments", schema=None) as batch_op:
        batch_op.drop_index("ix_shipments_status")
        batch_op.drop_index("ix_shipments_state")
        batch_op.drop_index("ix_shipments_ship_date")
        batch_op.drop_index("ix_shipments_recipient_name")
        batch_op.drop_index("ix_shipments_last_event_at")
        batch_op.drop_index("ix_shipments_carrier")

    op.drop_table("shipments")
    op.drop_table("settings")
    op.drop_table("jobs")
    op.drop_table("geocode_cache")
    op.drop_table("egress_log")
    with op.batch_alter_table("column_presets", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_column_presets_header_signature"))

    op.drop_table("column_presets")
    op.drop_table("carrier_credentials")
    # ### end Alembic commands ###
